"""initial

Revision ID: 264d5bed2c82
Revises: 4033d71c6355
Create Date: 2025-02-04 15:46:29.847865

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "264d5bed2c82"
down_revision: Union[str, None] = "4033d71c6355"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "note_database", sa.Column("data3", sa.String(length=100), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("note_database", "data3")
    # ### end Alembic commands ###
