"""initial

Revision ID: 4033d71c6355
Revises: 3e936e6adc69
Create Date: 2025-02-04 15:46:05.763756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4033d71c6355'
down_revision: Union[str, None] = '3e936e6adc69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_database', sa.Column('data2', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note_database', 'data2')
    # ### end Alembic commands ###
