"""Initial revision

Revision ID: 4618c19b1904
Revises: 
Create Date: 2025-02-08 14:14:16.206553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4618c19b1904'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_database',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('executor', sa.String(length=100), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('data_of_close', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note_database')
    # ### end Alembic commands ###
