"""whatever

Revision ID: 53dd9fe8f992
Revises: 502aa7445012
Create Date: 2025-02-07 09:19:34.002530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53dd9fe8f992'
down_revision: Union[str, None] = '502aa7445012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_database', sa.Column('author', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note_database', 'author')
    # ### end Alembic commands ###
