"""+visible+executor

Revision ID: c330fc2c1fcc
Revises: e5ce8480206c
Create Date: 2025-02-07 10:01:20.305116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c330fc2c1fcc'
down_revision: Union[str, None] = 'e5ce8480206c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note_database', sa.Column('data_of_close', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note_database', 'data_of_close')
    # ### end Alembic commands ###
